### ISSUE TITLE
Error al procesar archivos CSV y mapa de etiqueta.pbtxt: IndexError

### ISSUE THREAD

**Issue by ferjeff11** [FerJeffQ/Movil-Object-Detection#1]
**Descripción**

Estoy intentando ejecutar un código en Python que se encarga de crear archivos CSV y un mapa de etiqueta.pbtxt. Sin embargo, me encuentro con un error consistente que impide que el proceso se complete con éxito. A continuación, detallo el error que estoy enfrentando:

**Error**
`IndexError: child index out of range`

**Código relacionado**
Copy code

```python
for label_path in ['etiquetas_train', 'etiquetas_validation']:
  image_path = os.path.join(os.getcwd(), label_path)
  xml_df, classes = xml_to_csv(label_path)
  xml_df.to_csv(f'{label_path}.csv', index=None)
  print(f'Se convirtió los datos {label_path} xml to csv.')
```

Y en particular, el error ocurre en la función xml_to_csv en la línea:

`int(member[4][0].text),`

**Comment by FerJeffQ** [comment]
Que tal, tal ves sea el tipo de etiquetado recuerda que es PASCAL VOC formato:   .xml

**Comment by FerJeffQ** [comment]
Que tal, 
Es el tipo de etiquetado recuerda que es PASCAL VOC formato:   .xml
